---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS Prometheus controller is a service controller for managing Prometheus resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Prometheus
description: |-
  Manage Prometheus resources in AWS from within your Kubernetes cluster.


  **About Amazon Managed Service for Prometheus**


  Amazon Managed Service for Prometheus is a serverless, Prometheus-compatible monitoring service for container metrics that makes it easier to securely monitor container environments at scale. With Amazon Managed Service for Prometheus, you can use the same open-source Prometheus data model and query language that you use today to monitor the performance of your containerized workloads, and also enjoy improved scalability, availability, and security without having to manage the underlying infrastructure.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: RuleGroupsNamespace
  spec: '{}'
- kind: Workspace
  spec: '{}'
maintainers:
- name: "prometheus maintainer team"
  email: "ack-maintainers@amazon.com"
links: 
- name: Amazon Prometheus Developer Resources
  url: https://aws.amazon.com/prometheus/resources
